env:
  browser: true
  es6: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  require-jsdoc: off
  quotes:
    - error
    - double
  max-len:
    - error
    - code: 120
