---

language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - tiled

cache:
  - npm

install:
  - npm install

jobs:
  include:
    - stage: Lint
      script:
        - npm run lint
    - stage: Build
      script:
        - # npm run build
