---

version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install tiled
          command: |
            sudo apt-get install tiled
            npm install
      - run:
          name: Fake test
          command: |
            # npm run lint
            # npm run build
