---

version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install tiled
          command: |
            sudo apt-get install tiled
            npm install
      - run:
          name: Linter
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            # npm run build
